name: End to end test
on:
  push:
    branches:
      - main

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: look into env
        run: echo $PWD; find .
      - name: Create k8s kind cluster
        uses: helm/kind-action@v1.3.0
        with:
          config: ./kind-config.yaml
          wait: 3m
      - name: Setup ingress controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=90s
      - name: Build image
        run: docker build -t simple-app:snapshot ./simple-image
      - name: Upload image
        run: |
          kind get clusters
          kind get nodes
          kind load docker-image simple-app:snapshot
      - name: Deploy stuff
        run: |
          kubectl apply -f deployment.yaml
      - name: Wait until ready
        run: |
          while ! curl -f localhost:7180
          do
            sleep 5
            echo "wait 5s"
          done
        timeout-minutes: 1
      - name: Call URL
        run: curl -f localhost:7180
